New steps added in the release step
10up/.github pull request #25
Opened 2022-12-08 15:44 UTC by faisal-alvi

### Description of the Change
After the recent experience with the SLA release, it is felt that we should add a new step in the release checklist so that maintainers do not forget to take a pull of the `develop` branch in their local system after merging the Release PR. More on this [here](https://github.com/10up/simple-local-avatars/pull/178#issuecomment-1342849681).

### How to test the Change
Just check the changed markdown file.

### Changelog Entry
> Added - New release checklist step.

### Credits

Props @faisal-alvi 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-12-08 15:47 UTC, jeffpaul commented on CONTRIBUTING.md
> +9. Push: Push your `trunk` branch to GitHub (e.g. `git push origin trunk`).
I actually have another step after this that I tend to check myself (as I've run into issues in the past here) where I compare develop>trunk to ensure I didn't miss any changes.  So could add:
> 1. [Compare develop and trunk](https://github.com/10up/simple-local-avatars/compare/trunk...develop) to ensure no additional changes were missed.

2022-12-08 15:48 UTC, jeffpaul commented on CONTRIBUTING.md
> +9. Push: Push your `trunk` branch to GitHub (e.g. `git push origin trunk`).
Noting the link here is an example from SLA

2022-12-08 15:53 UTC, faisal-alvi commented on CONTRIBUTING.md
> +9. Push: Push your `trunk` branch to GitHub (e.g. `git push origin trunk`).
https://github.com/10up/.github/pull/25/commits/92a5c355286877c523823a610c80f933d89135ac

Added this:

_10. Compare develop and trunk to ensure no additional changes were missed. Visit [REPOSITORY_URL]/compare/trunk...develop_

Please let me know if any changes are required.

2022-12-08 20:13 UTC, dkotter requested changes

2022-12-08 20:13 UTC, dkotter commented on CONTRIBUTING.md
> +8. Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `trunk` (`git checkout trunk && git merge --no-ff develo
So thinking about this again, I believe the order of these steps is wrong. There's nothing to pull into `develop` until after the release PR is merged into `develop`. I'd suggest removing the newly added step 7 and making the following change to this step:

```suggestion
8. Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `trunk`, ensuring you pull the most recent changes into `develop` first (`git checkout develop && git pull origin develop && git checkout trunk && git merge --no-ff develop`). `trunk` contains the stable development version.
```

2022-12-09 15:34 UTC, dkotter commented on CONTRIBUTING.md
> +9. Compare develop and trunk to ensure no additional changes were missed. Visit [REPOSITORY_URL]/compare/trunk...develop
```suggestion
9. Compare `trunk` to `develop` to ensure no additional changes were missed. Visit [REPOSITORY_URL]/compare/trunk...develop
```

2022-12-09 15:35 UTC, dkotter commented on CONTRIBUTING.md
> +10. Test the pre-release ZIP locally by downloading it from the **Build release zip** action artifact to ensure the plugin doesn't break after release.
```suggestion
10. Test the pre-release ZIP locally by downloading it from the **Build release zip** action artifact and installing it locally. Ensure this zip has all the files we expect, that it installs and activates correctly and that all basic functionality is working.
```

2022-12-09 15:39 UTC, dkotter approved these changes

2022-12-09 17:51 UTC, merged

2022-12-09 17:52 UTC, jeffpaul commented
Great work further tweaking the process here, much appreciated!